export const LIST_PHONG_VE_REQUEST = "@dat-cho/LIST_PHONG_VE_REQUEST"
export const LIST_PHONG_VE_SUCCESS = "@dat-cho/LIST_PHONG_VE_SUCCESS"
export const LIST_PHONG_VE_FAILED = "@dat-cho/LIST_PHONG_VE_FAILED"