export const SIGN_UP_THEO_PHIM_REQUEST = "@dang-ky/SIGN_UP_THEO_PHIM_REQUEST"
export const SIGN_UP_THEO_PHIM_SUCCESS = "@dang-ky/SIGN_UP_THEO_PHIM_SUCCESS"
export const SIGN_UP_THEO_PHIM_FAILED = "@dang-ky/SIGN_UP_THEO_PHIM_FAILED"