export const SIGN_UP_TRANG_CHU_REQUEST = "@dang-ky/SIGN_UP_TRANG_CHU_REQUEST"
export const SIGN_UP_TRANG_CHU_SUCCESS = "@dang-ky/SIGN_UP_TRANG_CHU_SUCCESS"
export const SIGN_UP_TRANG_CHU_FAILED = "@dang-ky/SIGN_UP_TRANG_CHU_FAILED"