export const LOGIN_TRANG_CHU_REQUEST = "@login/LOGIN_TRANG_CHU_REQUEST"
export const LOGIN_TRANG_CHU_SUCCESS = "@login/LOGIN_TRANG_CHU_SUCCESS"
export const LOGIN_TRANG_CHU_FAILED = "@login/LOGIN_TRANG_CHU_FAILED"